import re
import os
import datetime
import csv
import requests
import secrets
from flask import Flask, request, session, jsonify, render_template
import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

# Google OAuth imports
import google_auth_oauthlib.flow
import google.auth.transport.requests
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

app = Flask(__name__)
app.secret_key = "my_super_secret_key"

# ------------------ STORING RSVPS -------------------
import sqlite3  # For storing RSVPs

DB_PATH = "rsvp.db"


def init_db():
    """Initialize the RSVP database with a table."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS rsvp (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT UNIQUE NOT NULL
        )
    """)
    conn.commit()
    conn.close()


init_db()  # Ensure DB is initialized at startup


# ------------------ EVENT DETAILS -------------------
EVENT_NAME = "Dr. Wanjiru at 60  🎉"
EVENT_DATE = "2025-05-03 13:30:00"  # Format: YYYY-MM-DD HH:MM:SS
EVENT_LOCATION = "Ankole Grill, Kitusuru"
EVENT_DURATION = 7  # in hours

SCOPES = ["https://www.googleapis.com/auth/gmail.send"]


# ------------------ CALENDAR INVITE FUNCTIONS -------------------
def create_ics_file(email):
    """
    Generate a .ics file content with event details.
    """
    start_time = datetime.datetime.strptime(EVENT_DATE, "%Y-%m-%d %H:%M:%S")
    end_time = start_time + datetime.timedelta(hours=EVENT_DURATION)

    # description_text = (
    #     "You're invited to Wanjiru’s 60th Birthday Party!\n\n"
    #     "Click here to RSVP:\n"
    #     "https://myapp.com/rsvp?event=wanjiru60&email={email}\n\n"
    #     "We’d love to know if you can make it!"
    # )

    ics_content = f"""BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
SUMMARY:Dr. Wanjiru’s surprise Birthday Party 🎉
DTSTART:{start_time.strftime('%Y%m%dT%H%M%S')}
DTEND:{end_time.strftime('%Y%m%dT%H%M%S')}
LOCATION:{EVENT_LOCATION}
DESCRIPTION:You are invited! 🎉
ORGANIZER;CN="Elizabeth":mailto:Elizabeth@gmail.com
ATTENDEE;CN="{email}";RSVP=TRUE:mailto:{email}
REMINDER_TIME = datetime.datetime.strptime(EVENT_DATE, "%Y-%m-%d %H:%M:%S") - datetime.timedelta(hours=48)
END:VEVENT
END:VCALENDAR
"""
    return ics_content


# ------------------ GMAIL SENDING SETUP -------------------
def get_gmail_credentials():
    """
    Load & refresh (if needed) the Gmail API credentials from token.json.
    token.json must be generated by running get_gmail_token.py once.
    """
    creds = Credentials.from_authorized_user_file("token.json", SCOPES)
    if creds.expired and creds.refresh_token:
        creds.refresh(google.auth.transport.requests.Request())
    return creds


def send_gmail_invite(to_email):
    """
    Send an email with a .ics calendar invite attached via Gmail API.
    """
    ics_str = create_ics_file(to_email)

    # 1) multipart message
    message = MIMEMultipart()
    message["to"] = to_email
    message["subject"] = f"🎉 You're Invited to {EVENT_NAME}"

    # 2) Plain text body
    body_text = (
        f"Hey! You are invited to Dr. Wanjiru's Surprise birthday Party!\n\n"
        f"📅 Date: {EVENT_DATE}\n"
        f"📍 Location: {EVENT_LOCATION}\n\n"
        "See attached calendar invite! Click to add to calendar. "
    )
    part_text = MIMEText(body_text, "plain", _charset="utf-8")
    message.attach(part_text)

    # 3) .ics attachment as base64
    part_ics = MIMEBase("text", "calendar", charset="utf-8")
    part_ics.set_payload(ics_str.encode("utf-8"))  # convert to bytes
    encoders.encode_base64(part_ics)  # base64-encode
    part_ics.add_header("Content-Transfer-Encoding", "base64")
    part_ics.add_header(
        "Content-Disposition", "attachment", filename="event-invite.ics"
    )
    part_ics.add_header("Content-Class", "urn:content-classes:calendarmessage")

    message.attach(part_ics)

    # 4) Convert entire message to base64 for Gmail
    raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode("utf-8")
    body = {"raw": raw_message}

    # 5) Send via Gmail
    creds = get_gmail_credentials()
    service = build("gmail", "v1", credentials=creds)
    try:
        result = service.users().messages().send(userId="me", body=body).execute()
        print("Email sent! Message ID:", result["id"])
        return True
    except Exception as e:
        print("Error sending via Gmail API:", e)
        return False


# def send_gmail_reminder(to_email):
#     """
#     Sends a reminder email 48 hours before the event.
#     """
#     message = MIMEMultipart()
#     message["to"] = to_email
#     message["subject"] = f"⏳ Reminder: {EVENT_NAME} in 48 hours!"

#     # Email body
#     body_text = (
#         f"Hey! Just a friendly reminder that {EVENT_NAME} is happening soon!\n\n"
#         f"📅 Date: {EVENT_DATE}\n"
#         f"📍 Location: {EVENT_LOCATION}\n\n"
#         "See you there! 🎉"
#     )
#     part_text = MIMEText(body_text, "plain", _charset="utf-8")
#     message.attach(part_text)

#     # Convert to base64 for Gmail API
#     raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode("utf-8")
#     body = {"raw": raw_message}

#     # Send email using Gmail API
#     creds = get_gmail_credentials()
#     service = build("gmail", "v1", credentials=creds)
#     try:
#         result = service.users().messages().send(userId="me", body=body).execute()
#         print("Reminder sent! Message ID:", result["id"])
#         return True
#     except Exception as e:
#         print("Error sending reminder:", e)
#         return False


# ------------------ CHAT MESSAGES & FLOW ------------------
MESSAGES = {
    "intro": (
        "🎉🤫 <strong>TOP SECRET BIRTHDAY INVITE</strong> 🤫🎉<br><br>"
        "Shhh... You’ve received a <strong>special</strong> invitation! 🕵️‍♀️<br><br>"
        "But first… Can you keep a secret?<br><br>"
        "Reply with:<br>"
        "1️⃣ 'Yes'<br>"
        "2️⃣ 'No'"
    ),
    "waiting_for_booking": (
        "📅 Are you <strong>booked</strong> on <strong>May 3rd</strong>?<br><br>"
        "Type:<br>"
        "1️⃣ 'Yes'<br>"
        "2️⃣ 'No'"
    ),
    "asking_friends": (
        "🤔 Are we <strong>friends</strong>?<br><br>" "Type:<br>1️⃣ 'Yes'<br>2️⃣ 'No'"
    ),
    "email_prompt": (
        "🥳 You are booked now! 🎉<br><br>"
        "📧 Please enter your <strong>email</strong> so we can send a calendar invite."
    ),
    "email_confirm": (
        "🎉 Boom! Your exclusive invite is on its way to <strong>{email}</strong>! 🚀<br><br>"
        "<strong>Kindly check your spam folder if it's not in your inbox✨</strong> <br><br>"
        "📅 Mark your calendar and get ready for an unforgettable surprise!<br><br>"
        "🤫 But remember... this is top-secret intel. No leaks, no hints, no spoilers! 🕵🏽‍♀️🔎<br><br>"
        "📞 Need to whisper a change of plans? Reach out to our undercover event agent, "
        "<strong>Elizabeth, at +61123456789.</strong><br><br>"
        "We can’t wait to celebrate—see you there! 🥳🎂🎊"
    ),
    "invalid_email": (
        "⚠️ That doesn’t look like a valid email.<br>"
        "Please enter a valid email address 📧"
    ),
    "no_worries": (
        "😊 No worries at all! If plans change, just give us a heads-up. ✨<br><br>"
        "Wishing you a fantastic day ahead! 🌞🎉<br><br>"
        "📞 If you need to reach us, our undercover event agent,<strong>Elizabeth, "
        "is just a call away at +61123456789.</strong>"
    ),
    "didnt_understand": (
        "I didn't understand that.<br>"
        "Type <strong>Secret</strong> to start again. 🔄"
    ),
}


# ------------------ json protection? ------------------
def restore_files_from_env():
    # Decode credentials.json
    creds_b64 = os.environ.get("CREDENTIALS_JSON_B64")
    token_b64 = os.environ.get("TOKEN_JSON_B64")
    if creds_b64:
        with open("credentials.json", "wb") as f:
            f.write(base64.urlsafe_b64decode(creds_b64))
    if token_b64:
        with open("token.json", "wb") as f:
            f.write(base64.urlsafe_b64decode(token_b64))

restore_files_from_env()


# ------------------ RSVP STORAGE? ------------------
def store_rsvp(email):
    """
    Store RSVP emails in the database.
    """
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("INSERT INTO rsvp (email) VALUES (?)", (email,))
        conn.commit()
    except sqlite3.IntegrityError:
        print(f"Email {email} already exists in RSVP list.")
    finally:
        conn.close()


# ------------------ FLASK ROUTES ------------------
@app.route("/")
def index():
    """Serve the main chat page (pinned layout with save-the-date overlay)."""
    return render_template("index.html")


@app.route("/chat", methods=["POST"])
def chat():
    """
    AJAX endpoint for front-end to send a user's message and receive the bot's reply.
    We'll store the user's state in the Flask session.
    """
    user_message = request.json.get("message", "").strip()

    # If user restarts or is new
    if "state" not in session or user_message.lower() == "secret":
        session["state"] = "waiting_for_secret"
        return jsonify({"reply": MESSAGES["intro"]})

    current_state = session["state"].lower()
    lower_msg = user_message.lower()

    # Handle "waiting_for_email" -> validate email
    if current_state == "waiting_for_email":
        if re.match(r"[^@]+@[^@]+\.[^@]+", lower_msg):
            # Valid email -> send ICS invite via Gmail
            send_gmail_invite(lower_msg)
            session.pop("state", None)
            reply = MESSAGES["email_confirm"].format(email=user_message)
            return jsonify({"reply": reply})
        else:
            return jsonify({"reply": MESSAGES["invalid_email"]})

    # waiting_for_secret
    if current_state == "waiting_for_secret":
        if lower_msg in ["1", "yes"]:
            session["state"] = "waiting_for_booking"
            return jsonify({"reply": MESSAGES["waiting_for_booking"]})
        elif lower_msg in ["2", "no"]:
            return jsonify({"reply": MESSAGES["asking_friends"]})

    # waiting_for_booking
    if current_state == "waiting_for_booking":
        if lower_msg in ["2", "no"]:
            session["state"] = "waiting_for_email"
            return jsonify({"reply": MESSAGES["email_prompt"]})
        elif lower_msg in ["1", "yes"]:
            return jsonify({"reply": MESSAGES["no_worries"]})

    # Fallback
    return jsonify({"reply": MESSAGES["didnt_understand"]})


@app.route("/rsvp", methods=["GET"])
def rsvp():
    """
    Handles custom RSVP links.
    E.g. /rsvp?event=wanjiru60&email=someone@domain.com
    We'll show a simple page/form where the user chooses Yes/No/Maybe.
    """
    email = request.args.get("email", "")
    event_name = request.args.get("event", "")
    return f"""
    <html>
    <head><title>RSVP for {event_name}</title></head>
    <body>
      <h2>RSVP for {event_name}</h2>
      <p>Hey {email}, let us know if you can make it!</p>
      <form action="/rsvp_submit" method="post">
        <input type="hidden" name="email" value="{email}">
        <input type="hidden" name="event" value="{event_name}">
        <button type="submit" name="rsvp" value="Yes">Yes</button>
        <button type="submit" name="rsvp" value="No">No</button>
        <button type="submit" name="rsvp" value="Maybe">Maybe</button>
      </form>
    </body>
    </html>
    """


@app.route("/rsvp_submit", methods=["POST"])
def rsvp_submit():
    """
    Receives the form submission from /rsvp.
    Expects 'email', 'event', and 'rsvp' fields in POST data.
    """
    email = request.form.get("email", "")
    event_name = request.form.get("event", "")
    rsvp_choice = request.form.get("rsvp", "")  # "Yes", "No", or "Maybe"

    # Store the result in a CSV (or DB, if you prefer)
    store_rsvp(event_name, email, rsvp_choice)

    # Display a basic thank-you page
    return f"""
    <html>
      <body>
        <h3>Thanks, {email}!</h3>
        <p>Your RSVP for {event_name} is <strong>{rsvp_choice}</strong>.</p>
      </body>
    </html>
    """


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=True)
